### ISSUE TITLE
Update to express 4.0

### ISSUE THREAD

**Issue by lo1tuma** [rendrjs/rendr#357]
express 4.0 has been released recently. It has some great [new features](https://github.com/visionmedia/express/wiki/New-features-in-4.x) and improvements. 
Especially the new router would be interesting for rendr, it is more flexible and allows you to `use` other routers easily.

**Comment by saponifi3d** [comment]
tied to: https://github.com/rendrjs/rendr/issues/422 - going to start working on this update tomorrow.

**Comment by growlsworth** [comment]
Cool. Thanks @saponifi3d.

**Comment by saponifi3d** [comment]
@growlsworth - it's a belated bday present :package:

**Comment by growlsworth** [comment]
:)
