### ISSUE TITLE
Example Tests

### ISSUE THREAD

**Issue by crwang** [rendrjs/rendr#413]
Hi all,

I've been looking for examples on how to write tests in Rendr for things like testing our controllers, models, and collections.  So far, from what I've seen on the examples, there isn't too much there.

Has anyone written some tests for their apps that they can share.  I'd love to be able to test our models and collections connecting to the APIs and/or test retrieving data at the controller level.

Any help would be greatly appreciated!

Thanks

**Comment by saponifi3d** [comment]
@crwang - yes!..ish. I still haven't figured out a great way to test controllers yet - mainly because of how they're implemented.  I do have some model / view / collection tests for examples.

(I'm using mocha / chai).

model (or collection):
```js
var App = require('app/app'),
    Model = require('myModel'),
    expect = require('chai').expect;

describe('MyModel', function () {
  beforeEach(function () {
    // any other setup code for each model
    subject = new Model(undefined, {app: new App()});
  });

  describe('aFunctionInModel', function () {
    // explicitly test the functions you need to limit the testing to your new functionality
    it('does something new', function () {
      expect(subject.aFunctionInModel()).to.be.true;
    });
  });
});
```

view:
```js
var expect = require('chai').expect,
    memo = require('memo-is');   // great for creating data attributes and testing it in different scopes

describe('MyView', function() {
  // again only test new functionality and try to not call things like: view.render()
  // your templates shouldn't have much logic in them, so testing them is less important
  // if you need to test a template - calling .render() then using chai-jquery to test functionality seems legit
});
```

to explicitly test controllers (which seems like is the meat of what you want to do based on your question) is rather difficult.  Here's a quick idea for how you could test them though...
```js
var expect = require('chai').expect,
      sinon = require('sinon'),
      memo = require('memo-is'),
      App = require('app/app'),
      subject = require('controller');

describe('my controller', function () {
  beforeEach(function () {
    subject.app = new App();
  });
  describe('index', function () {
    var cb = sinon.spy(),
        params = memo().is(function() {
          return { id: 1 };
        });

      it('calls the cb w/ the data', function () {
        var expectedResult = new Model(1);
        subject.index(params(), cb);

        expect(cb).to.have.been.calledWith(expectedResult);
        expect(subject.app.get('title')).to.equal('index title');
      });
   });
});
```

(sorry for any spacing issues with the above code.. just wrote it out in the comment tool)

**Comment by pjanuario** [comment]
So far so good, I have been able to test everything but now I was trying to do an integration test and it seems that we are unable to test controller that execute this.app.fetch due to name resolution. :/

```
  1) VenueController index should fetch first 10 venues:
     Error: Cannot find module 'app/collections/venues'
      at Function.Module._resolveFilename (module.js:338:15)
      at Function.Module._load (module.js:280:25)
      at Module.require (module.js:364:17)
      at ModelUtils.require (module.js:380:17)
      at ModelUtils.fetchConstructor 
      /node_modules/rendr/shared/modelUtils.js:77:17)
```

It seems the problem is related with the venue controller test be running in the path test/app/controllers. 

Any clue on this?

**Comment by saponifi3d** [comment]
yeah, you'll need to set the paths to work correctly.  What I've done is just not used relative pathing like `app/collections/venues` opting for either using `app.getCollection()` or a full path require instead.

**Comment by pjanuario** [comment]
I was actually asking myself if instantiating models and collections using "new" would be the best approach, probably using app.getCollection and app.getModel would solve a lot of issues.

**Comment by visaHB** [comment]
Hi, Could anyone share what framework or tool are you using for your integration testing esp to test the frontend of your application? I have been trying to use different framework with phantomJs2 but facing issues with supporting the new phantomjs2.

**Comment by saponifi3d** [comment]
hey @visaHB i'm using karma to test the front-end stuff, similar to this: https://github.com/rendrjs/rendr-examples/tree/master/06_appview/test and then everything is just standard mocha / chai testing on the server side.

**Comment by bigethan** [comment]
We use busterJS with https://www.npmjs.com/package/buster-functional for unit and functional testing

**Comment by pjanuario** [comment]
We are currently working with the same tools as @saponifi3d but we the difference we are run client code using mocha and rerun using karma. We have 100% coverage and the entire spec suite takes about 5sec to run and almost half of the time is browserify bundle.

**Comment by pjanuario** [comment]
@bigethan this tools seems nice, it seems similar to capybara/ruby. How are you handling the api calls? Are mocking on specs or do you launch a api test server?

**Comment by bigethan** [comment]
Currently we have an api server running as we don't have a good way to mock data for our functional testing (giant complex search dataset with nuanced use cases). We were using https://github.com/pgte/nock before we had an API.  It's almost too smart for it's own good, but does what it says very well.

**Comment by visaHB** [comment]
Thank you for the information, I came across nightwatchjs for e2e testing. Has anyone used it before? Would busterjs be better for e2e or nightwatchjs?

**Comment by bigethan** [comment]
When we looked at Selenium, it was pretty bad for mobile web testing, and our Rendr app is mobile only. Not sure what your needs are.  Buster's server makes it easy to run on actual devices/emulators.  We haven't automated things up with saucelabs yet (And I'm sure there will be pain there), but it's quite possible. We've also been experimenting with http://appium.io, where you use chrome as the app and that's been *ok*

**Comment by visaHB** [comment]
@bigethan I decided to try my hands at buster-functional, however being new to it I am unable to run the test cases written with buster-functional. I do understand a config file is required but following the config file example given at https://www.npmjs.com/package/buster-functional, I am still unable to get the tests running. Do you have any suggestion how I can actually get it running? Thank you

**Comment by alexindigo** [comment]
@visaHB Did you add the part related to Rendr? There is section in the bottom part of the Readme file.

And what kind of errors do you get?

**Comment by visaHB** [comment]
@alexindigo You are referring to the section about the 'setup' for rendr based applications rite? Yup I did include them. However, whenever I try to use the assert eg: assert.className(this.$('.btn-primary.postal-code')); it throws me exception as follows:  Cannot read property 'className' of undefined.
I am unable to assert and when I remove the assert statements and simply fails indicating there is No assertions!

**Comment by alexindigo** [comment]
Can you show your test file? So we'd be able to better debug your problem. Thank you.

**Comment by visaHB** [comment]
@alexindigo you can find my test file here: https://github.com/visaHB/busterTesting

I was finally able to run the sample test, however now my issue is that I am unable to assert using the assert contains and by the time I enter value into the text field the browser where the testing is done quickly moves on and hence I am unable to see the enter input. Including a wait for this still doesn't help. Thank you

**Comment by alexindigo** [comment]
@visaHB To see the results, you can wrap your `done` invocation in `setTimeout`, actual tests not meant to be human observed, so there is no default delay.

As for postal code typing. Both `.type` and `.click` are asynchronous, so it starts clicking before you enter the whole postal.

Call `.click` within `.type`'s callback. it will do the trick.

**Comment by visaHB** [comment]
@alexindigo Thank you and how about the assertion for contains? the assert.contains is still throwing me an exception, on my browser console with: $('.error-msg.alert-zone-error-msg-home').text() I am able to get the desired text however, when I run the test it always say expected [] to contain Enter your 6-digit postal code
So I am not sure what should be done to validate if the error message is found

**Comment by alexindigo** [comment]
I didn't see `assert.contains` there so it's hard to diagnose the problem. Would you mind to put the code in question to the example? I mean the actual file that it failing for you? Thank you.

**Comment by visaHB** [comment]
@alexindigo oops I am sorry I forgot to commit my changes, and yes now you can see how I had used assert.contains, thank you

**Comment by alexindigo** [comment]
@visaHB – since everything is running async, this callback https://github.com/visaHB/busterTesting/blob/master/simpleTest-test.js#L29-L35 will be executed sometimes between first and second character typed into the field, and when I tried manually reproduce it, I've got following:

```
$('.form-control.tb-postal-code-home').val()
// -> "2"

$('.error-msg.alert-zone-error-msg-home').text()
// -> ""

$('.btn.btn-primary.save-postal-code-home-change').click()

$('.error-msg.alert-zone-error-msg-home').text()
// -> "That postal code is not valid for Singapore"
```

So if you want to test error message with no input, try to remove `.type()` statement.

Then I noticed another thing, on lines https://github.com/visaHB/busterTesting/blob/master/simpleTest-test.js#L44-L45 you're trying to assert something right after you invoked `.click`, but without waiting for it to finish, is it done on purpose, or you meant to wait for click operation to finish and perform assert within `click`'s callback?

**Comment by visaHB** [comment]
@alexindigo here is what I was trying with the code:
So as you mentioned, I do understand that with the type statement at https://github.com/visaHB/busterTesting/blob/master/simpleTest-test.js#L29-L35 , the callback can happen before the typing is done, however in that case i should still have another error message which as you had indicated would be "That postal code is not valid for Singapore" but even in this case I still get:

 expected [] to contain Enter your 6-digit postal code

Shouldn't this be then expected "That postal code is not valid for Singapore" to contain "Enter your 6-digit postal code". Also, even without the type statement(commenting out that line ) I constantly get the same exception: expected [] to contain Enter your 6-digit postal code.

And yes, i was intentionally trying to assert without waiting after the .click as I wanted to see if my .click was getting executed in the first place. At https://github.com/visaHB/busterTesting/blob/master/simpleTest-test.js#L45-L48 is what I tested first and it passed but https://github.com/visaHB/busterTesting/blob/master/simpleTest-test.js#L50-L54 failed. So to understand what was going on I tried without the callback and realised the first was working as the class is also found on the page before the click is executed.

**Comment by visaHB** [comment]
I guess I might need more time to explore and probably get the hang of busterJs and this might not be the best forum to discuss the issues I might be facing with it, so maybe I will shift my queries to the busterJS forum. Thank You people for your help :)

**Comment by alexindigo** [comment]
I cloned your sample repo and it didn't work right out of the box, can you give me more details on how you run it? And what you're using to load code into the browser?

As for BusterJS, easiest way to get in tough with them is freenode IRC #buster.js room.
