### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by saponifi3d** [rendrjs/rendr#422]
https://david-dm.org/rendrjs/rendr

Need to update:
* express(*)
* underscore
* request

(*) To do this I believe we need to drop Node 0.8 support.  Anyone have any thoughts on dropping support for 0.8? @spikebrehm @bigethan @lo1tuma @c089 @alexindigo

**Comment by spikebrehm** [comment]
I'm down to drop 0.8 support -- does that mean we should increment the major version, as it's backwards incompatible?  We should stop being scared of the 1.x release anyway, it's just a number.

**Comment by saponifi3d** [comment]
i was thinking 1.x we could do with view agnostic stuff? i'm still side projecting that... (aka it's getting little to no work right now :p).

I'd be down to version bump to 1.x or 0.6 though.

**Comment by spikebrehm** [comment]
Yeah, it would be awesome to get the view agnostic stuff in a "1.x", but i
like the strict semver approach i.e. Browserify takes -- they're on 7.x

**Comment by saponifi3d** [comment]
:+1: v1.0 dropping node 0.8 and adding express 4 sounds good.  This will *hopefully* not take tooooo long.
