### ISSUE TITLE
Documentation Site

### ISSUE THREAD

**Issue by saponifi3d** [rendrjs/rendr#429]
@spikebrehm I'm going to start working on a bit more in-depth docs and make them in the style of backbone docs (for now sans the annotated source).

I was thinking of using github pages, but i see there is already one. Care if I do an iterative style and update the docs and merge them as I go or would you rather that I open a big ol' pr to `gh-pages` and update it all at once? (or not use `gh-pages` at all)

**Comment by saponifi3d** [comment]
Hmm looking into it a bit more it looks like i can create a repo named `rendrjs.github.io` - and have that link to `rendrjs.github.io` instead of `rendrjs.github.io/rendr` for now. then we can talk about swapping it over later.

**Comment by spikebrehm** [comment]
Sounds great!

**Comment by spikebrehm** [comment]
To be more clear -- makes sense to do `rendrjs.github.io`. But if you wanted to nuke the `gh-pages` branch, be my guest -- i just auto-generated that from the README

**Comment by saponifi3d** [comment]
okay cool i'll just do that. i was playing around with the `rendr.github.io` thing and it blew up in my face. haha.
