### ISSUE TITLE
The link of examples on the main page is broken. 

### ISSUE THREAD

**Issue by Amit-Kolambikar** [rendrjs/rendr#445]
The link of examples https://github.com/rendrjs/rendr/tree/master/examples  on [main site](http://rendrjs.github.io/rendr/)  page is broken.

**Comment by saponifi3d** [comment]
Oh weird! okay, that site is actually out of date (I should probably take it down and have it redirect to here: http://rendrjs.github.io/)

Thanks for letting me know!

**Comment by saponifi3d** [comment]
Made the github page on /rendr redirect to the main site for now.
