### ISSUE TITLE
1.0.4 does not find 'handlebars' module, breaks example apps

### ISSUE THREAD

**Issue by skanaar** [rendrjs/rendr#475]
When upgrading to RendrJS 1.0.4 our app breaks with the message `Cannot find module 'handlebars'`.
Can be reproduced by installing the example apps, which also fails when using 1.0.4

**Comment by ingiulio** [comment]
Hey @skanaar, since Rendr 1.0.4 we need to have `handlebars` as a dependency in our app's `package.json`. 
E.g.

```
// /package.json

"dependencies": {
  ...
  "express": "^4.12.3",
  "handlebars": "^2.0.0"
  "qs2": "~0.6.6",
  ...
},
```

The docs were updated here: http://rendrjs.github.io/app/#config
I forgot to update the example apps, sorry about that (PR coming soon).

**Comment by ingiulio** [comment]
PR opened: https://github.com/rendrjs/rendr-examples/pull/20

**Comment by saponifi3d** [comment]
This issue should be fixed now, thanks for reporting it!
