### ISSUE TITLE
Fetch timeout parameter gets filtered

### ISSUE THREAD

**Issue by ErikLarsson82** [rendrjs/rendr#480]
Hi,

I'm trying to implement standard timeout functionality when doing client requests.

So, passing options { timeout: 1337 } to app.fetch seems like a good idea.

The problem I have is that those options gets filtered in fetcher.js. In fact, the only option that gets passed to the actual fetch is headers.

Now, one simple modification and the timeout parameter gets passed all the way down the chain to the actual xhr request and I get the behaviour I expect.
Line 178, fetcher.js
-> timeout: options.timeout, //maybe a nullcheck here aswell

Is this a change that is in the pipeline? Or am I approaching the problem from some wrong angle? I'd love to provide a pull request if neccessary.

Thanks in advance ^_^

**Comment by saponifi3d** [comment]
:+1: i like your PR that you opened! thanks for the question, sorry i didn't get back to you in time before you answered it yourself. :)
