### ISSUE TITLE
A way to update template from view after invoke this.app.fetch(spec, callback)

### ISSUE THREAD

**Issue by TylerYang** [rendrjs/rendr#486]
Hi Guys,
I just use rendr created a small app but I got stuck when I try to update the template from view.

Here is the full picture,

myView:
<pre>
module.exports = BaseView.extend({
events: {
     "keyup #searchInput": updateDetail
},
updateDetail: function(){
    var searchVal = $("#searchInput").val();
    var _params = {
        q: searchVal,
        _type: "search"
    };
    var spec = {
        collection: {
               collection: "Books"
        }
    };
    this.app.fetch(spec, function(err, result){
        if(err) handleError(err);
        //.. how can I update template here.?
    });
}
});

</pre>

Should I use the handlebars and manipulate DOM inside the fetch callback?(e.g $("#container").html("blahblah") ?)

Can somebody do me a favor? Thx.

**Comment by skanaar** [comment]
Please consider using a Questions and Answers forums (like StackOverflow for example) for questions about how to use the framework.

But the short answer to your questions is that you should implement a `getTemplateData()` function and call the view's `render()` function.

**Comment by TylerYang** [comment]
Thx. I will do it next time.

**Comment by pjanuario** [comment]
@saponifi3d I think we can close this!

**Comment by saponifi3d** [comment]
@pjanuario awesome, thanks for the heads up.
