### ISSUE TITLE
12 tests failing

### ISSUE THREAD

**Issue by ErikLarsson82** [rendrjs/rendr#487]
Hi, 
I cloned the repo from 1.1.0 (hash 5ee8b4a).

#mocha test/*
180 passing (797ms)
12 failing

Am I missing something or is the repo in the state that it's acceptable that some tests are failing?
Im doing a pull request and hope to add some tests, can I simply ignore the one currently failing?

Thanks!

**Comment by pjanuario** [comment]
The build seems to be green on that tag: https://travis-ci.org/rendrjs/rendr/builds/66471320

**Comment by ErikLarsson82** [comment]
I ran this instead (found in package.json)
#mocha -R spec ./test --recursive

... and now i got 333 passed and none failing. Thank you for your help!

**Comment by crwang** [comment]
@ErikLarsson82 just a side note, you should be able to just run `npm test` as is specified in the package.json instead of explicitly running mocha.  :)

**Comment by ErikLarsson82** [comment]
@crwang I had the feeling that I missed something simple like that. Noted! Thanks :+1:
