### ISSUE TITLE
Add Gitter badge so we can chat

### ISSUE THREAD

**Issue by crwang** [rendrjs/rendr#489]
@saponifi3d 

I'm wondering if we can add a gitter badge for rendrjs/rendr, rendrjs/rendr-examples.

@alexindigo and I are working on a requirejs bundles grunt plugin and an approach that in my opinion really makes rendr shine and it'd be good to chat about it.  I'm hoping too to chat with you about it and see if you think it'd work for you and maybe we can create a gulp one as well since I know you're on gulp.

Also, is there a way we can add more collaborators at least to the `rendr-examples` repo?  I have a PR pending and theres another one pending up there.  I would like to get those cleaned up and documented better so that it's easier for people to get started using rendr.

I think Rendr, especially with the requirejs bundles is extremely performant and it'd be awesome to lessen the ramp up time for people to have a great app out there and to drive more adoption.  

Thanks!!

**Comment by crwang** [comment]
Also, it'd be great if we could contribute to the Wiki :smile:

**Comment by saponifi3d** [comment]
@spikebrehm ^ thoughts?

Sorry, yeah I only really look at rendrjs/rendr, the others i kinda wait for someone to poke me about because PRs are so infrequent.  If you just @ tag me I'm pretty responsive about things since it will actually email me and poke me that way, you can also do the @ rendrjs/maintainers to tag everyone that's a maintainer for a review.

As for the wiki, maybe we just create a "best practices" section in https://github.com/rendrjs/rendrjs.github.io ?  That way we can have a conical place that is still PR'd to make sure everyone agrees with it and all that jazz.

I'll go ahead and take a look at the example you posted, sorry for the delay!! As I was saying, feel free to @ tag me.

**Comment by crwang** [comment]
Thanks @saponifi3d !  I just want to push this forward and smooth over some of the rough edges so the barrier to entry is lower and we can get some more high caliber engineers and companies on the platform.

I wish github had a way to do PRs on the wiki.

A best practices section would work.  I just need to work on getting that set up.

I'm also thinking we should probably push people to ask questions on SO.  I think that would increase the attention of Rendr and it's just a good platform for Q & A in general.

**Comment by saponifi3d** [comment]
100% agree about Stack. I've been trying to get Change.org to ask all questions (internal / external) about Rendr on Stack too. There are already tags setup and everything... just need to start getting questions. :+1: 

Thanks for all the work on that stuff, I'm really curious to see what you come up with along the requirejs lines as I've only done a couple toy projects with it + rendr to get a better understand of PRs I'm looking at, so I haven't seen it's true power yet.

**Comment by crwang** [comment]
We'll keep you posted.  It's mostly Alex, I'm just trying to help so that we can get it open sourced and usable by the community.  :)

**Comment by pjanuario** [comment]
@crwang Nice!

**Comment by spikebrehm** [comment]
> Also, is there a way we can add more collaborators at least to the rendr-examples repo?

@crwang you bet -- glad to add you as a contributor if you promise to do good things

**Comment by crwang** [comment]
@spikebrehm :+1: 

I'm all about doing good things.  :smile: 

Would you mind adding the rendr-examples repo into the rendr-examples-contributors team? Thanks for helping get us set up.

**Comment by spikebrehm** [comment]
@crwang done :+1:

**Comment by crwang** [comment]
Thanks!  I added gitter to the rendr-examples repo.  I'll leave you or Josh to set up the https://gitter.im/rendrjs/rendr room when you all have time.

Alex and I are getting excited about getting the require js example updated and with requirejs bundles (uglified and asset versioned).  It should be a solid boost in performance and we're trying to make it as easy to adopt and setup as possible!

**Comment by crwang** [comment]
@saponifi3d would you mind signing up for gitter.im?  I'd love to be able to bounce some ideas off of you in a dedicated channel.  I tried adding you to the conversation but you're not on there.  :grimacing:
