### ISSUE TITLE
Production environment

### ISSUE THREAD

**Issue by tomblos** [rendrjs/rendr#490]
Hello, I´m trying to deploy a rendr.js app on IIS with iisnode. Iisnode is working fine with another, non rendr.js app, but I can´t get the rendr app to work. The error message I get from iisnode is unfortunately very general (Internal Server Error) without details. 

Has anyone managed to do this? I would appreciate any input on what steps needs to be done e.g. changes in index.js or similar, when moving the rendr.js app to production environment.

Thanks!!
Andreas

**Comment by crwang** [comment]
Sorry Andreas, I do know that I tried about a year ago to see if I could deploy onto IIS, but after about an hour or so, I gave up and just pushed to Heroku.

**Comment by tomblos** [comment]
Thank you crwang, I´ll go ahead and try that as well.

**Comment by tomblos** [comment]
Heroku worked as a charm, I´m very impressed. Thanks for the tip @crwang

**Comment by crwang** [comment]
:+1:
