### ISSUE TITLE
Rendr, Grunt and Browserify

### ISSUE THREAD

**Issue by sQVe** [rendrjs/rendr#492]
Hello fellow Rendr nerds,

We've been running our app with the following versions of browserify and grunt-browserify:

```
    "browserify": "2.36.1",
    "grunt-browserify": "1.2.12",
```

As you can see they are quite old and but I've been struggling to update them - I can simply not get it to work. Does anyone have a **good example** for building a Rendr app with an updated version of Browserify? Or is it possible to update the examples to use a newer version, as they use an even older version.

Appreciate all the help that can be given!
Cheers

**Comment by pjanuario** [comment]
@sQVe I also have been struggling this a couple of months ago and it's on my queue to pick again, the main issue that I found was related with aliasMappings configuration, didn't find any way to do it. Should be a solution somewhere but I didn't found it yet.

**Comment by sQVe** [comment]
@pjanuario I have the same choke point, cannot seem to get alias mapping to work. There are other issues too but alias mapping seems to be the main culprit.

Been googling quite heavily but haven't found any good resources for building with grunt/gulp and browserify.

**Comment by wvengen** [comment]
I haven't been able to go beyond these yet
```json
{
    "browserify-shim": "~3.8.10",
    "grunt-browserify": "~2.1.4",
    "remapify": "~1.3.0",
    "browserify": "~11.2.0"
}
```

**Comment by sQVe** [comment]
@wvengen That's pretty close to fully updated tho. Care to care your setup/config?

**Comment by wvengen** [comment]
@sQVe I discovered that I'm actually using browserify 4.2.3 :( (somewhere hidden in `node_modules`).
Trying to extract a bare-bones project, I find browserify not being able to resolve `require`s anymore, really strange. But if I manage to isolate the cause, I'll definitely post.

**Comment by saponifi3d** [comment]
So, I've used gulp + browserify a bunch in the past, which is handy because of streams vs intermediate files.  I need to add an example of how to use gulp for the build process one of these days.. adding the documentation flag so i remember to update the examples later for this.

Generally, i'm not quite sure where you are running into road blocks.  Also, fwiw, I started using webpack not too long ago in conjunction with gulp, so i can just farm everything out to webpack and then have it go through a couple extra steps in production deploying.

**Comment by pjanuario** [comment]
@saponifi3d Nice, would be awesome to have a example with webpack.

**Comment by alexindigo** [comment]
@saponifi3d Are you using webpack with Rendr?

**Comment by webdevisme** [comment]
@saponifi3d That would be ace to see, I'm just hitting the same issue myself :(
