### ISSUE TITLE
Lazy view with fetch_params

### ISSUE THREAD

**Issue by wvengen** [rendrjs/rendr#494]
I'm trying to use a lazy-loaded view using `fetch_params`. With rendr-handlebars in the view:

```handlebars
{{view "foo" lazy=true collection_name='Products' fetch_params=params}}
```

and `params` something like `{category_id: 12, q: "bar"}` (a search query). I can't get this lazy view to work.

It seems that on the server-side, `fetch_params` are known. On the client, however, they are lost. Looking at [BaseView#getAttributes](https://github.com/rendrjs/rendr/blob/83ae5cb3fd3c205873ac8d97a1cb131662cc2f0b/shared/base/view.js#L142), only non-object parameters are stored in the dom; neither does `fetch_params` become part of [fetch_summary](https://github.com/rendrjs/rendr/blob/83ae5cb3fd3c205873ac8d97a1cb131662cc2f0b/shared/base/view.js#L546).
When making `fetch_params` a json-string instead of an object, [BaseView#fetchLazy](https://github.com/rendrjs/rendr/blob/83ae5cb3fd3c205873ac8d97a1cb131662cc2f0b/shared/base/view.js#L234) complains.

Am I the first to use this functionality, or am I missing something?

**Comment by saponifi3d** [comment]
You need to JSON.stringify the params because it's going to just say "Object object" as the fetch_params otherwise

**Comment by wvengen** [comment]
Thanks.

For others reading this: somehow using rendr-handlebar's `json` helper didn't work. I needed to cast it to a `String` or else the resulting fetch params in the view's data attribute would still be empty.

```handlebars
{{view "foo/list" lazy=true model_name="Product" fetch_params=(jsons product_query}}
```

with `product_query` a simple object like `{q: 'bar'}`, and in my handlebars helpers:
```js
   /*
    * Return object serialized as JSON.
    *
    * Same as rendr-handlebars' `json` but also cast to a string. Somehow this
    * is needed or else it isn't serialized.
    */
   jsons: function(object, spacing) {
     return String(JSON.stringify(object, null, spacing || 'null'));
   }
```
