### ISSUE TITLE
Rendr + jspm

### ISSUE THREAD

**Issue by ram-you** [rendrjs/rendr#507]
Hi, 
can someone provide us an example or a simple approach to compile a Rendr project with jspm.
Thank you.

**Comment by saponifi3d** [comment]
Hmm, I haven't actually used jspm before, project looks pretty interesting.  It seems like it's a replacement for using browserify or webpack?  you probably need a polyfill for CommonJS / AMD requires. https://www.npmjs.com/package/jspm-loader might do the trick

**Comment by ram-you** [comment]
Thank you @saponifi3d .
